"""'pirma'

Revision ID: 28bdb648b2be
Revises: 
Create Date: 2022-02-24 19:33:41.503333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bdb648b2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vartotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Vartotojo vardas', sa.String(length=100), nullable=False),
    sa.Column('El.paštas', sa.String(length=100), nullable=False),
    sa.Column('Slaptažodis', sa.String(length=100), nullable=False),
    sa.Column('Nuotrauka', sa.String(length=100), nullable=True),
    sa.Column('Administratorius', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('El.paštas'),
    sa.UniqueConstraint('Vartotojo vardas')
    )
    op.create_table('masina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamintojas', sa.String(length=50), nullable=False),
    sa.Column('modelis', sa.String(length=50), nullable=True),
    sa.Column('metai', sa.String(length=8), nullable=True),
    sa.Column('variklis', sa.String(length=50), nullable=True),
    sa.Column('valst_nr', sa.String(length=8), nullable=True),
    sa.Column('reg_nr', sa.String(length=30), nullable=True),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sukurta', sa.DateTime(), nullable=True),
    sa.Column('problema', sa.String(length=200), nullable=False),
    sa.Column('Suma', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['masina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irasas')
    op.drop_table('masina')
    op.drop_table('vartotojas')
    # ### end Alembic commands ###
