"""'du'

Revision ID: 4235ad1c57f4
Revises: 28bdb648b2be
Create Date: 2022-02-26 11:43:58.495706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4235ad1c57f4'
down_revision = '28bdb648b2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamintojas', sa.String(length=50), nullable=False),
    sa.Column('modelis', sa.String(length=50), nullable=True),
    sa.Column('metai', sa.String(length=8), nullable=True),
    sa.Column('variklis', sa.String(length=50), nullable=True),
    sa.Column('valst_nr', sa.String(length=8), nullable=True),
    sa.Column('reg_nr', sa.String(length=30), nullable=False),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('masina')
    op.drop_table('irasas')
    op.add_column('vartotojas', sa.Column('Darbuotojas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vartotojas', 'Darbuotojas')
    op.create_table('irasas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Sukurta', sa.DATETIME(), nullable=True),
    sa.Column('problema', sa.VARCHAR(length=200), nullable=False),
    sa.Column('Suma', sa.NUMERIC(precision=16, scale=2), nullable=True),
    sa.Column('vartotojas_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['masina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masina',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gamintojas', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modelis', sa.VARCHAR(length=50), nullable=True),
    sa.Column('metai', sa.VARCHAR(length=8), nullable=True),
    sa.Column('variklis', sa.VARCHAR(length=50), nullable=True),
    sa.Column('valst_nr', sa.VARCHAR(length=8), nullable=True),
    sa.Column('reg_nr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('vartotojas_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('masinos')
    # ### end Alembic commands ###
